- menu_name: "Links"

#- name: "Contact"
#  url: "/contact/"
#  title: "Contact"

- name: "RSS"
  url: "http://terrylansdown.github.io/atom.xml"
  title: "Subscribe to RSS Feed"

#- name: "RSS"
#  url: "/atom.xml"
#  title: "Subscribe to Atom Feed"

- name: "Site XML"
  url: "/sitemap.xml"
  title: "Sitemap for Google Webmaster Tools"
